coverage fixed

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -264,8 +264,15 @@ jobs:
               echo "lint files changed. running lint"
               # python file (CommonServerPython lint is running over python 3 and 2)
               # we use `demisto-sdk` because we're inside content local env and not on poetry local env
-              demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPython
-              
+              demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPython --coverage-report ./test_coverage
+
+              if [[ -f ./test_coverage/html/index.html && -f ./test_coverage/test/coverage.xml ]]
+              then
+                echo "coverage files found."
+              else
+                echo "coverage files not found."
+                exit 1
+              fi              
               # ps file
               demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPowerShell
               
