add graph-tests job

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,7 +64,7 @@ jobs:
           mkdir test-results
           # poetry run pytest --ignore={demisto_sdk/commands/init/templates,demisto_sdk/tests/integration_tests} --store-durations --junitxml=test-results/junit.xml || pytest_exit_code=$
           # mv .test_durations test-results/test_durations
-          poetry run pytest -v --ignore={demisto_sdk/commands/init/templates,demisto_sdk/tests/integration_tests} --cov=demisto_sdk --cov-report=html --junitxml=test-results/junit.xml --splits 5 --group ${{ matrix.group }} || pytest_exit_code=$?
+          poetry run pytest -v --ignore={demisto_sdk/commands/init/templates,demisto_sdk/tests/integration_tests,demisto_sdk/commands/content_graph} --cov=demisto_sdk --cov-report=html --junitxml=test-results/junit.xml --splits 5 --group ${{ matrix.group }} || pytest_exit_code=$?
           echo "PYTEST_EXIT_CODE=$pytest_exit_code" >> $GITHUB_ENV
 
           kill $node_pid
@@ -168,6 +168,79 @@ jobs:
             echo "There are integration-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the tests summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
           else
             echo "All integration-tests have passed, congratulations!"
+          fi
+          exit $PYTEST_EXIT_CODE
+  graph-tests:
+    name: Graph Tests / ${{ matrix.python-version }} (${{ matrix.group }})
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [ "3.8", "3.9", "3.10" ]
+      fail-fast: false
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Setup Poetry
+        run: |
+          sudo curl -sSL https://install.python-poetry.org | python3 -
+          poetry --version
+          poetry check --lock
+          poetry install -E generate-unit-tests
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+
+      - name: Install npm
+        run: |
+          npm install
+          echo $(echo '{"node_version": "'$(node --version)'","npm_list":'$(npm list --json)'}') > node_versions_info.json
+
+      - name: Run pytest
+        run: |
+          source "$(poetry env info --path)/bin/activate"
+
+          mkdir graph-test-results
+          poetry run pytest -v demisto_sdk/commands/content_graph --cov=demisto_sdk --cov-report=html --junitxml=graph-test-results/junit.xml || pytest_exit_code=$?
+          echo "PYTEST_EXIT_CODE=$pytest_exit_code" >> $GITHUB_ENV
+
+      - name: Upload artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: graph-tests-artifacts-${{ matrix.python-version }}
+          path: |
+            test-results/test_durations
+            graph-test-results/junit.xml
+            node_versions_info.json
+            coverage_html_report
+            .coverage
+      - name: Print Summary of pytest results in workflow summary
+        if: always()
+        uses: pmeier/pytest-results-action@main
+        with:
+          path: graph-test-results/junit.xml
+          summary: true
+          display-options: fsEX
+          fail-on-empty: true
+      - name: Check if tests have passed
+        if: always()
+        run: |
+          if [[ "$PYTEST_EXIT_CODE" -ne 0 ]]; then
+            echo "There are graph-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the tests summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
+          else
+            echo "All graph-tests have passed, congratulations!"
           fi
           exit $PYTEST_EXIT_CODE
 
