coverage in case of failures

diff --git a/.github/workflows/run_unit_tests.yml b/.github/workflows/run_unit_tests.yml
--- a/.github/workflows/run_unit_tests.yml
+++ b/.github/workflows/run_unit_tests.yml
@@ -75,6 +75,10 @@ jobs:
           # poetry run pytest $TEST_FILES --store-durations
           mkdir test-results
           poetry run pytest $TEST_FILES -v --cov=demisto_sdk --cov-report=html --junitxml=test-results/junit.xml --splits 5 --group ${{ matrix.group }}
+          
+          pytest_exit_code=$?
+          echo "PYTEST_EXIT_CODE=$exit_code" >> $GITHUB_ENV
+          
           kill $node_pid
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
@@ -85,6 +89,11 @@ jobs:
             test-results/junit.xml
             node_versions_info.json
             coverage_html_report
-      - name: Check exit code of Step 1
-        run: exit 1
-        if: ${{ failure() }}
+      - name: Validate if pytest has passed
+        run: |
+          if [ "$PYTEST_EXIT_CODE" -ne 0 ]; then
+            echo "There are unit-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE"
+          else
+            echo "All unit-tests have passed"
+            # Add actions or commands for success
+          fi
