add integration-tests

diff --git a/.github/workflows/run_unit_tests.yml b/.github/workflows/run_unit_tests.yml
--- a/.github/workflows/run_unit_tests.yml
+++ b/.github/workflows/run_unit_tests.yml
@@ -14,7 +14,7 @@ concurrency:
 
 
 jobs:
-  tests:
+  unit-tests:
     name: Unit Tests / ${{ matrix.python-version }} (${{ matrix.group }})
     runs-on: ubuntu-latest
     strategy:
@@ -92,6 +92,79 @@ jobs:
         run: |
           if [[ "$PYTEST_EXIT_CODE" -ne 0 ]]; then
             echo "There are unit-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the tests summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
+          else
+            echo "All unit-tests have passed"
+          fi
+          exit $PYTEST_EXIT_CODE
+
+  integration-tests:
+    name: Integration Tests / ${{ matrix.python-version }} (${{ matrix.group }})
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [ "3.8", "3.9", "3.10" ]
+      fail-fast: false
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Setup Poetry
+        run: |
+          sudo curl -sSL https://install.python-poetry.org | python3 -
+          poetry --version
+          poetry check --lock
+          poetry install
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '14'
+
+      - name: Install npm
+        run: npm install
+
+      - name: Run pytest
+        run: |
+          source "$(poetry env info --path)/bin/activate"
+  
+          # Due to race conditions in the tests bringing up and down the node server, have the server available
+          # For all the tests.
+
+          mkdir integration-test-results
+          poetry run pytest -v demisto_sdk/tests/integration_tests --cov=demisto_sdk --cov-report=html --junitxml=integration-test-results/junit.xml || pytest_exit_code=$?
+          echo "PYTEST_EXIT_CODE=$pytest_exit_code" >> $GITHUB_ENV
+
+          exit $pytest_exit_code
+      - name: Upload artifacts
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: coverage-${{ matrix.os }}-${{ matrix.python_version }}
+          path: |
+            .test_durations
+            integration-test-results/junit.xml
+            coverage_html_report
+      - name: Print Summary of pytest results in workflow summary
+        if: always()
+        uses: pmeier/pytest-results-action@main
+        with:
+          path: integration-test-results/junit.xml
+          summary: true
+          display-options: fsEX
+          fail-on-empty: true
+      - name: Check if tests have passed
+        if: always()
+        run: |
+          if [[ "$PYTEST_EXIT_CODE" -ne 0 ]]; then
+            echo "There are integration-tests that failed, pytest finished with exit code $PYTEST_EXIT_CODE, to see the tests summary refer to https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
           else
             echo "All unit-tests have passed"
           fi
